{{- $csp := .Values.ocis.csp | default dict -}}
{{- if ($csp.enabled | default false) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocis-subpath.fullname" . }}-csp
  labels:
    {{- include "ocis-subpath.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  csp.yaml: |
    directives:
{{ include "ocis-subpath.cspDirectives" . | indent 6 }}
{{- end }}
