{{- if .Values.traefik.enabled }}
{{- $fullname := include "ocis-subpath.fullname" . -}}
{{- $labels := include "ocis-subpath.labels" . -}}
{{- $subpath := include "ocis-subpath.normalizedSubpath" . | trim -}}
{{- $externalIDP := .Values.ocis.oidc.external.enabled -}}
{{- $routePrefix := "" -}}
{{- if ne $subpath "/" -}}
{{- $routePrefix = $subpath -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullname }}-strip-subpath-prefix
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: ingress-middleware
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  stripPrefix:
    prefixes:
      - {{ $subpath }}
---
{{- end }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullname }}-drop-auth-header
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: ingress-middleware
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  headers:
    customRequestHeaders:
      Authorization: ""
---
{{- if not $externalIDP }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullname }}-wellknown
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: ingress
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- toYaml .Values.traefik.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.traefik.hosts }}
    - match: Host(`{{ .host }}`) && PathPrefix(`{{ $routePrefix }}/.well-known`)
      kind: Rule
      priority: 200
      services:
        - name: {{ $fullname }}-idp
          port: 9130
    {{- end }}
  tls: {{ toJson .Values.traefik.tls }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullname }}-idp
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: ingress
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- toYaml .Values.traefik.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.traefik.hosts }}
    - match: Host(`{{ .host }}`) && (PathPrefix(`{{ $routePrefix }}/signin`) || PathPrefix(`{{ $routePrefix }}/konnect`))
      kind: Rule
      priority: 205
      services:
        - name: {{ $fullname }}-idp
          port: 9130
    {{- end }}
  tls: {{ toJson .Values.traefik.tls }}
---
{{- end }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullname }}-capabilities
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: ingress
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- toYaml .Values.traefik.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.traefik.hosts }}
    - match: Host(`{{ .host }}`) && (Path(`{{ $routePrefix }}/ocs/v2.php/cloud/capabilities`) || Path(`{{ $routePrefix }}/ocs/v1.php/cloud/capabilities`))
      kind: Rule
      priority: 190
      middlewares:
        {{- if ne $subpath "/" }}
        - name: {{ $fullname }}-strip-subpath-prefix
        {{- end }}
        - name: {{ $fullname }}-drop-auth-header
      services:
        - name: {{ $fullname }}-frontend
          port: 9140
    {{- end }}
  tls: {{ toJson .Values.traefik.tls }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullname }}-frontend
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: ingress
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- toYaml .Values.traefik.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.traefik.hosts }}
    - match: Host(`{{ .host }}`) && (Path(`{{ $routePrefix }}/app`) || PathPrefix(`{{ $routePrefix }}/app/`) || Path(`{{ $routePrefix }}/archiver`) || PathPrefix(`{{ $routePrefix }}/archiver/`))
      kind: Rule
      priority: 185
      {{- if ne $subpath "/" }}
      middlewares:
        - name: {{ $fullname }}-strip-subpath-prefix
      {{- end }}
      services:
        - name: {{ $fullname }}-frontend
          port: 9140
    {{- end }}
  tls: {{ toJson .Values.traefik.tls }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullname }}-api
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: ingress
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- toYaml .Values.traefik.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.traefik.hosts }}
    - match: Host(`{{ .host }}`) && (PathPrefix(`{{ $routePrefix }}/graph`) || PathPrefix(`{{ $routePrefix }}/api`) || PathPrefix(`{{ $routePrefix }}/dav`) || PathPrefix(`{{ $routePrefix }}/data`) || PathPrefix(`{{ $routePrefix }}/remote.php`) || PathPrefix(`{{ $routePrefix }}/ocs`) || PathPrefix(`{{ $routePrefix }}/thumbnails`))
      kind: Rule
      priority: 180
      {{- if ne $subpath "/" }}
      middlewares:
        - name: {{ $fullname }}-strip-subpath-prefix
      {{- end }}
      services:
        - name: {{ $fullname }}
          port: {{ $.Values.service.port }}
    {{- end }}
  tls: {{ toJson .Values.traefik.tls }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullname }}-web
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: ingress
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- toYaml .Values.traefik.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.traefik.hosts }}
    - match: Host(`{{ .host }}`) && PathPrefix(`{{ $subpath }}`)
      kind: Rule
      priority: 100
      services:
        - name: {{ $fullname }}
          port: {{ $.Values.service.port }}
    {{- end }}
  tls: {{ toJson .Values.traefik.tls }}
{{- end }}
