{{- if and (not .Values.ocis.existingSecret) .Values.ocis.generatedSecrets.enabled }}
{{- $name := include "ocis-subpath.fullname" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "ocis-subpath.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  {{ .Values.ocis.secrets.adminPasswordKey }}: {{ default (randAlphaNum 24) (dig "data" .Values.ocis.secrets.adminPasswordKey "" $existing | b64dec) | quote }}
  {{ .Values.ocis.secrets.jwtSecretKey }}: {{ default (randAlphaNum 48) (dig "data" .Values.ocis.secrets.jwtSecretKey "" $existing | b64dec) | quote }}
  {{ .Values.ocis.secrets.transferSecretKey }}: {{ default (randAlphaNum 48) (dig "data" .Values.ocis.secrets.transferSecretKey "" $existing | b64dec) | quote }}
  {{ .Values.ocis.secrets.machineAuthApiKeyKey }}: {{ default (randAlphaNum 48) (dig "data" .Values.ocis.secrets.machineAuthApiKeyKey "" $existing | b64dec) | quote }}
{{- end }}
